### ISSUE TITLE
m17x

### ISSUE THREAD

**Issue by trackmastersteve** [trackmastersteve/alienfx#1]
I'm running the **Kali Linux 2.0** (**Debian**) and I cant get the GUI to run so i can create themes. The CLI works fine, but I have no way to create themes that way. After installing this, all of my lights went off and I have no way to fix it now!

**Comment by trackmastersteve** [comment]
I was able to restore the **default** theme from the source-zip (somehow it was deleted). Now, if only I could create new themes in the CLI since the GUI is not working. **EDIT**: I can change colors by editing the **theme** text file. But there doesnt seem to be an option for the "**Alienhead**" on the **m17x**.

**Comment by ashwinm76** [comment]
Unfortunately, I no longer use Linux, and my Alienware M14x laptop is not actively used either. So I have no way at the moment to debug and fix this problem. I'm sorry that I can't be of more help to you.

**Comment by trackmastersteve** [comment]
I created another file for the **m17x** and an **import** for that file as well. And I got it working pretty good from the CLI at least. But I noticed there is no option for the "**Alienhead**"  and the power button doesn't actually change color. I've been trying to search for those "zone codes" to fix the issue. Maybe you could point me in the right direction.

**Comment by trackmastersteve** [comment]
Also, I might have figured out why I can't load the **GUI**. I launched the **GUI** from the command line and I can see the errors. It says I didn't specify a **GTK Version**. Do you happen to know what version you originally wrote this for? Or at least the Linux Distro Verion?

**EDIT**: I got the **GUI** working (I was still missing the **cairo** package). But I still see the "**GTK Version**" error even though it loads now.

**Comment by ashwinm76** [comment]
Regarding the power button, I snooped the control codes for the M14x by using Wireshark with USBPcap on windows to see what codes Dell's windows app was sending to the controller (in fact this is how I reverse engineered the codes for all the zones). I also remember that the windows app that Dell shipped didn't allow full control of the power button (probably due to limitations in the LED controller on the motherboard). 

As for the alien head on the lid, as far as I could tell, there was no control whatsoever on it. It was probably hardwired to the screen backlight on the M14x.

I developed and tested this on Linux Mint 16 cinnamon (64 bit), and when I moved to Arch later (around 2014) it worked there too. I do remember seeing several GTK errors when the program was run from the command line, though I don't remember what those errors were. I didn't bother with them since they didn't seem to affect the program.

**Comment by trackmastersteve** [comment]
Thanks for the info! I'm not much of a python programmer yet, but I have created a couple modifications to get things working on the m17x. I tried to submit those to this git project, but it forked it onto my page instead (I'm new to Git as well). Sorry if I'm doing it wrong. And I really appreciate all the work that went into this project so far. I found that all the zones are backwards on the m17x (right keyboard is actually left, etc.). I'll try and see what else I can contribute to this project. Thanks again!

**Comment by ashwinm76** [comment]
This was in fact my first (and only) Python project, so I'm glad that you're finding it useful. When you do get it working to your satisfaction on your machine, I'll be happy to accept any code contributions you want to make. In fact, since I'm no longer actively using Linux or an Alienware machine, I'd be happy to transfer the ownership of this repository to you if you're willing to take it.

**Comment by trackmastersteve** [comment]
I'm still trying to learn python. But I'll take the project and see what I can do with it.

**Comment by trackmastersteve** [comment]
Thanks for accepting the Pull request. I found that all the keyboard zones are backwards on the m17x compared to the way you have them for the m14x (i.e. Left Keyboard = Right Keyboard etc). Not sure If I should change that, because that would make them wrong on the m14x. So I'll just leave it for now. Still trying the find the zone code for the Alienhead and power button on the m17x as well.

**Comment by ashwinm76** [comment]
Try swapping the zone codes at the top of your controller file.

**Comment by trackmastersteve** [comment]
Thank you. I have fixed the zone codes on the m17x control file.
