### ISSUE TITLE
Adding Alien Head

### ISSUE THREAD

**Issue by trackmastersteve** [trackmastersteve/alienfx#6]
I found the zone code for the Alien Head. I've added it to the control files and it shows up on the GUI. But there is no color selection for that zone. I'm trying to figure out what I'm still missing.

**Comment by trackmastersteve** [comment]
Do you happen to have an idea of what I'm still missing?

**Comment by ashwinm76** [comment]
Could you elaborate on what you mean when you say that there is no colour selection for the zone? Does the GUI not let you set a colour? Or is the colour you set not getting applied to the alien head? Does it get applied if you hand-edit the theme file with the colours you want for the alien head?

**Comment by trackmastersteve** [comment]
The GUI does not let me set a color. There is no "currently set color" square next to that name.

**Comment by ashwinm76** [comment]
Off the top of my head, I can't think why it won't work, your code looks fine. Did you copy the default theme (with the addition for the alien head colour) to your theme directory before starting the gui?

**Comment by ashwinm76** [comment]
Also, if you've already set a theme before (i.e. before you added the alien head zone), then you might have to manually add in the alien head colour from the default theme file into the last theme file (called .last_theme.json in ~/.config/alienfx or in $XDG_CONFIG_HOME/alienfx) before the gui can recognize it. Alternatively, whenever you modify the code, delete .last_theme.json before opening the gui. The gui may not be showing you the colour set for the alien head because it can't find an alien head zone in the theme file that it loaded.

**Comment by trackmastersteve** [comment]
Ah OK, that's makes sense now. Thank you! I don't know why I didn't think of that... I'll try it and post an update.

**Comment by trackmastersteve** [comment]
It worked! Thanks for the help! Now I just need to figure out why I can't change the power button color...

**Comment by trackmastersteve** [comment]
I fixed the Power button as well. I was just a glitch. All I did to fix it was unplug the power cable and plug it back in! XD
